# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            toddlerMusicBox
tagline:          'A toddler friendly music box'
description:      ''
url:              http://janfietz.github.io/toddlerMusicBox/

author:
  name:           'Jan Fietz'
  url:            https://github.com/janfietz

paginate:         5
gems:             [jekyll-paginate]

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/janfietz/toddlerMusicBox



defaults:
 - scope:
     path: "assets/images"
   values:
     image: true
